apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-test-test-rbac
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: provider-test
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/provider-test/test-rbac
    repoURL: https://github.com/cloud-native-toolkit-test/provider-test-tr2u0q.git
    targetRevision: main
    helm:
      valueFiles:
        - .tmp/rbac/provider-test/test-rbac/values.yaml
      releaseName: test-rbac
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
